# /pnpm-workspace.yaml
packages:
  # 所有在 apps 目录下的前端和后端项目
  - "apps/*/front-end"
  - "apps/*/back-end"

  - "packages/commons"
  - "packages/locale"

  - "packages/vendor/fuyeor/packages/commons"
  - "packages/vendor/fuyeor/packages/interactify"
  - "packages/vendor/fuyeor/packages/tsconfig"
  - "packages/vendor/fuyeor/packages/config"
